language: python
sudo: required
dist: xenial
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"

install:
  - travis_retry pip install "jinja2>=2.7" msgpack-python pyyaml pytest>=3.3.2 pytest-cov arrow
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then travis_retry pip install pint coveralls ply; fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then py.test tests/ --ignore=tests/contrib --cov=odin ; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then python setup.py test ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then coveralls; fi
